{u'description': [u'Personal overlay of Ben Longbons'],
 u'feeds': [u'https://github.com/o11c/ebuilds/commits/master.atom'],
 u'homepage': u'https://github.com/o11c/ebuilds',
 u'irc': None,
 u'name': u'o11c',
 u'official': False,
 u'owner_email': u'b.r.longbons@gmail.com',
 u'owner_name': u'Ben Longbons',
 u'priority': 50,
 u'quality': u'experimental',
 u'sources': [(u'git://github.com/o11c/ebuilds.git', u'Git', u''),
              (u'https://github.com/o11c/ebuilds.git', u'Git', u'')],
 u'status': u'unofficial',
 u'supported': True}
$ pmaint sync o11c
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
Already up-to-date.
*** syncing o11c
*** synced o11c
 * Sync succeeded
$ pmaint regen -t 2 o11c
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'

!!! ERROR: dev-python/attoconf-9999 failed.
!!! die invoked from directory /usr/lib64/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 457:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 209:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 440:  Called __ebd_process_metadata '174' 'depend'
!!!             ebuild-daemon.bash, line 373:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 431:  Called __load_ebuild '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!                     ebuild.lib, line 252:  Called __qa_invoke 'source' '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!           attoconf-9999.ebuild, line   5:  Called inherit 'distutils-r1' 'git-2'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'distutils-r1'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!            distutils-r1.eclass, line  85:  Called inherit 'multiprocessing' 'python-r1'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'python-r1'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!               python-r1.eclass, line  47:  Called die
!!! The die message:
!!!  Unsupported EAPI=4 (too old, allowed only on restricted set of packages) for python-r1

ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: dev-python/attoconf-9999
 * Cache regenerated successfully
