{'description': {'en': 'Personal overlay of Ben Longbons'},
 'feed': ['https://github.com/o11c/ebuilds/commits/master.atom'],
 'homepage': 'https://github.com/o11c/ebuilds',
 'name': 'o11c',
 'owner': [{'email': 'b.r.longbons@gmail.com',
            'name': 'Ben Longbons',
            'type': 'person'}],
 'quality': 'experimental',
 'source': [{'type': 'git', 'uri': 'git://github.com/o11c/ebuilds.git'},
            {'type': 'git', 'uri': 'https://github.com/o11c/ebuilds.git'}],
 'status': 'unofficial'}
$ pmaint sync o11c
WARNING:pkgcore:repository at '/home/mgorny/sync/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/sync/steveeJ' has unsupported profile format(s): 'profile-set'
Already up-to-date.
*** syncing o11c
*** synced o11c
 * Sync succeeded
$ pmaint regen --use-local-desc --pkg-desc-index -t 1 o11c
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'

!!! ERROR: dev-python/attoconf-9999 failed.
!!! die invoked from directory /home/mgorny/pkgcore-venv/lib/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 458:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 210:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 441:  Called __ebd_process_metadata '174' 'depend'
!!!             ebuild-daemon.bash, line 374:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 431:  Called __load_ebuild '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!                     ebuild.lib, line 252:  Called __qa_invoke 'source' '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!           attoconf-9999.ebuild, line   5:  Called inherit 'distutils-r1' 'git-2'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'distutils-r1'
!!!              ebuild-daemon.lib, line  23:  Called __qa_invoke '__preloaded_eclass_distutils-r1'
!!!         isolated-functions.lib, line 286:  Called __preloaded_eclass_distutils-r1
!!!             ebuild-daemon.bash, line 468:  Called inherit 'multiprocessing' 'python-r1'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'python-r1'
!!!              ebuild-daemon.lib, line  23:  Called __qa_invoke '__preloaded_eclass_python-r1'
!!!         isolated-functions.lib, line 286:  Called __preloaded_eclass_python-r1
!!!             ebuild-daemon.bash, line 430:  Called die
!!! The die message:
!!!  Unsupported EAPI=4 (too old, allowed only on restricted set of packages) for python-r1


!!! ERROR: dev-python/attoconf-9999 failed.
!!! die invoked from directory /home/mgorny/pkgcore-venv/lib/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 458:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 210:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 441:  Called __ebd_process_metadata '174' 'depend'
!!!             ebuild-daemon.bash, line 374:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 431:  Called __load_ebuild '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!                     ebuild.lib, line 252:  Called __qa_invoke 'source' '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/o11c/dev-python/attoconf/attoconf-9999.ebuild'
!!!           attoconf-9999.ebuild, line   5:  Called inherit 'distutils-r1' 'git-2'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'distutils-r1'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!            distutils-r1.eclass, line  85:  Called inherit 'multiprocessing' 'python-r1'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'python-r1'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!               python-r1.eclass, line  47:  Called die
!!! The die message:
!!!  Unsupported EAPI=4 (too old, allowed only on restricted set of packages) for python-r1

ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: dev-python/attoconf-9999
ERROR pkgcore: returned val from gen_metadata was 'False'
caught exception '%s' while processing '%s'(MetadataException('Metadata Exception: pkg ebuild src: dev-python/attoconf-9999, attr description\nerror: Metadata Exception: pkg ebuild src: dev-python/attoconf-9999, attr data\nerror: False',), <<class 'pkgcore.ebuild.ebuild_src.package'> cpv='dev-python/attoconf-9999' @0x7fa43e2647d0>)
 * Cache regen failed with 1
